// Regression tests use the actual embedded browser script, not a second implementation.
const fs = require('node:fs');
const source = fs.readFileSync(process.argv[2], 'utf8');
const begin = source.indexOf('<script>') + '<script>'.length;
const end = source.indexOf('</script>', begin);
if (begin < 8 || end < begin) throw Error('Embedded script missing');
const fake = "\n  const elements=new Map(), fakeTimers=[];\n  const makeElement=()=>({\n    children:[],dataset:{},className:'',textContent:'',style:{},clears:0,\n    classList:{add(){},remove(){},toggle(){}},\n    appendChild(child){this.children.push(child);},\n    addEventListener(){}, setPointerCapture(){},\n    getContext(){return {clears:0,clearRect(){this.clears++;},fillRect(){}};}\n  });\n  const document={hidden:false,getElementById(id){\n    if(!elements.has(id))elements.set(id,makeElement());return elements.get(id);\n  },createElement:makeElement,querySelectorAll(){return [];},addEventListener(){}};\n  const window={addEventListener(){},removeEventListener(){}};\n  const location={protocol:'http:',host:'192.168.1.38',search:''};\n  class WebSocket {\n    static OPEN=1;static CONNECTING=0;static CLOSED=3;\n    constructor(){this.readyState=0;this.sent=[];this.closed=false;}\n    send(s){this.sent.push(s);}\n    close(){this.closed=true;this.readyState=3;}\n  }\n  const setTimeout=(fn,delay)=>{const t={fn,delay};fakeTimers.push(t);return t;};\n  const clearTimeout=t=>{if(t)t.cancelled=true;};\n  const confirm=()=>true;\n  class URLSearchParams {constructor(search){this.search=search;}has(k){return this.search.includes(k);}}\n";
const assertions = "\n  const assert = (condition, message) => { if (!condition) throw Error(message); };\n  const current = socket;\n  current.readyState = WebSocket.OPEN;\n  current.onopen();\n  assert(current.sent.length === 0, 'Reload must not send default B');\n  current.onmessage({data:'S100100001'});\n  assert(buttonMask === 265, 'Server mask sync');\n  assert(current.sent.join(',') === 'L', 'First LCD request after sync');\n  const packet = new Uint8Array(98); packet[0]=253; packet.fill(32,1,33);\n  packet.set(asciiScreen(' 7.123MHz'+String.fromCharCode(5,7,6)+' 1,2','FWD=123  REF=4.5'),1);\n  packet[33+40]=7;\n  current.onmessage({data:packet.buffer});\n  assert(bytesToAscii(meterScreen,0,9)===' 7.123MHz','Fixed frequency');\n  assert(bytesToAscii(meterScreen,16,23)==='FWD=123','FWD live');\n  assert(bytesToAscii(meterScreen,25,32)==='REF=4.5','REF live');\n  assert(antennaGlyph(packet.subarray(33,97))[42]===7,'ANT2 synthesized');\n  assert(antennaGlyph(packet.subarray(33,97))[40]===7,'IntelliTune row live');\n  const changed = contexts.reduce((n,c)=>n+c.clears,0);\n  drawSnapshot(packet);\n  assert(contexts.reduce((n,c)=>n+c.clears,0)===changed,'Identical pixels skip redraw');\n  packet[33+56]=1;\n  drawSnapshot(packet);\n  assert(contexts.reduce((n,c)=>n+c.clears,0)>changed,'CGRAM redraw immediate');\n  const menu = new Uint8Array(98); menu[0]=253;\n  menu.set(asciiScreen('METER RANGE AUTO','SETUP MODE'),1);\n  drawSnapshot(menu);\n  assert(lastCellSignatures[0] === Array.from(FONT_ROWS.get(77)).join(','),'Menu appears on first snapshot');\n  const clear = new Uint8Array(98);clear[0]=253;clear.fill(32,1,33);\n  drawSnapshot(clear);\n  assert(lastCellSignatures.every(s=>s==='0,0,0,0,0,0,0,0'),'Clear has no stale labels');\n  const glyph = new Uint8Array(64);glyph[0]=1;\n  renderCell(0,8,glyph);\n  assert(lastCellSignatures[0]==='1,0,0,0,0,0,0,0','CGRAM aliases 8..15');\n  renderCell(0,0,glyph,true);\n  assert(lastCellSignatures[0]==='31,31,31,31,31,31,31,31','Tuning full blocks');\n  lcdRequestPending=false; current.sent=[];\n  setButton(1,true);\n  assert(current.sent[0].startsWith('B'),'Press command immediate');\n  setButton(1,false);\n  assert(current.sent[current.sent.length-2].startsWith('B') &&\n         current.sent[current.sent.length-1]==='L','Release before fresh LCD');\n  const watchdog = fakeTimers[fakeTimers.length-1];\n  const sends=current.sent.length;watchdog.fn();\n  assert(current.closed && current.sent.length===sends,'Timeout closes; no duplicate L');\n  current.readyState=WebSocket.CLOSED;\n  connect();\n  const signature = lastCellSignatures[0];\n  current.onmessage({data:packet.buffer});\n  assert(lastCellSignatures[0]===signature,'Stale connection ignored');\n  for(let code=32;code<127;code++)assert(FONT_ROWS.has(code),'ASCII coverage '+code);\n  return {tests:17, contexts:contexts.length, fontCharacters:FONT_ROWS.size};\n";
const result = new Function(fake + source.slice(begin,end) + assertions)();
console.log('Browser regression tests passed:', JSON.stringify(result));
